Update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -34,6 +34,15 @@ jobs:
       - name: Install Android SDK dan Build Tools
         run: sdkmanager "platforms;android-34" "build-tools;34.0.0"
 
+      - name: Install XML Validator
+        run: sudo apt-get install -y libxml2-utils
+
+      - name: Validate XML Files
+        run: |
+          for file in $(find app/src/main/res -name "*.xml"); do
+            xmllint --noout "$file" || (echo "❌ Error in $file" && exit 1)
+          done
+
       - name: Download OpenCV SDK
         run: |
           wget -O opencv-4.11.0-android-sdk.zip https://github.com/opencv/opencv/releases/download/4.11.0/opencv-4.11.0-android-sdk.zip
